src/print_result/cf_generator/cf_generator.h File Reference
#include <assert.h>
#include <ctype.h>
#include `print_result/is_valid/is_valid.h`
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
Macros
#define ZERO 0
#define ONE 1
#define TWO 2
#define THREE 3
#define FOUR 4
#define FIVE 5
#define SIX 6
#define SEVEN 7
#define EIGHT 8
#define NINE 9
#define TEN 10
#define ELEVEN 11
#define TWELVE 12
#define THIRTEEN 13
#define FOURTEEN 14
#define FIFTEEN 15
#define SIXTEEN 16
#define SEVENTEEN 17
#define EIGHTEEN 18
#define NINETEEN 19
#define TWENTY 20
#define TWENTYONE 21
#define TWENTYTWO 22
#define TWENTYTHREE 23
#define TWENTYFOUR 24
#define TWENTYFIVE 25
#define TWENTYSIX 26
#define THIRTYONE 31
#define ASCII 48
#define HUNDRED 100
#define THOUSAND 1000
#define MIN_YEAR 1900
#define MAX_YEAR 2017
#define EOS '\0'
#define A 'A'
#define B 'B'
#define C 'C'
#define D 'D'
#define E 'E'
#define F 'F'
#define G 'G'
#define H 'H'
#define I 'I'
#define J 'J'
#define K 'K'
#define L 'L'
#define M 'M'
#define N 'N'
#define O 'O'
#define P 'P'
#define Q 'Q'
#define R 'R'
#define S 'S'
#define T 'T'
#define U 'U'
#define V 'V'
#define W 'W'
#define X 'X'
#define Y 'Y'
#define Z 'Z'
#define CHAR_0 '0'
#define CHAR_1 '1'
#define CHAR_2 '2'
#define CHAR_3 '3'
#define CHAR_4 '4'
#define CHAR_5 '5'
#define CHAR_6 '6'
#define CHAR_7 '7'
#define CHAR_8 '8'
#define CHAR_9 '9'
Functions
void name_code (char name[], char *code)
void surname_code (char surname[], char *code)
void birth_date_code (char date[], char sex, char code[])
char ctrl_code (char coded_name[], char coded_surname[], char coded_birth_date[], char coded_birth_place[])
void cf_generator (char name[], char surname[], char birth_date[], char coded_town[], char sex, char code[])
Macro Definition Documentation
A
#define A 'A'
Definition at line 53 of file cf_generator.h.
ASCII
#define ASCII 48
Definition at line 47 of file cf_generator.h.
B
#define B 'B'
Definition at line 54 of file cf_generator.h.
C
#define C 'C'
Definition at line 55 of file cf_generator.h.
CHAR_0
#define CHAR_0 '0'
Definition at line 79 of file cf_generator.h.
CHAR_1
#define CHAR_1 '1'
Definition at line 80 of file cf_generator.h.
CHAR_2
#define CHAR_2 '2'
Definition at line 81 of file cf_generator.h.
CHAR_3
#define CHAR_3 '3'
Definition at line 82 of file cf_generator.h.
CHAR_4
#define CHAR_4 '4'
Definition at line 83 of file cf_generator.h.
CHAR_5
#define CHAR_5 '5'
Definition at line 84 of file cf_generator.h.
CHAR_6
#define CHAR_6 '6'
Definition at line 85 of file cf_generator.h.
CHAR_7
#define CHAR_7 '7'
Definition at line 86 of file cf_generator.h.
CHAR_8
#define CHAR_8 '8'
Definition at line 87 of file cf_generator.h.
CHAR_9
#define CHAR_9 '9'
Definition at line 88 of file cf_generator.h.
D
#define D 'D'
Definition at line 56 of file cf_generator.h.
E
#define E 'E'
Definition at line 57 of file cf_generator.h.
EIGHT
#define EIGHT 8
Definition at line 27 of file cf_generator.h.
EIGHTEEN
#define EIGHTEEN 18
Definition at line 37 of file cf_generator.h.
ELEVEN
#define ELEVEN 11
Definition at line 30 of file cf_generator.h.
EOS
#define EOS '\0'
Definition at line 52 of file cf_generator.h.
Referenced by cf_generator(), and ctrl_code().
F
#define F 'F'
Definition at line 58 of file cf_generator.h.
Referenced by is_valid_sex().
FIFTEEN
#define FIFTEEN 15
Definition at line 34 of file cf_generator.h.
Referenced by ctrl_code().
FIVE
#define FIVE 5
Definition at line 24 of file cf_generator.h.
Referenced by is_valid_date_code(), and read_birth_place_code().
FOUR
#define FOUR 4
Definition at line 23 of file cf_generator.h.
Referenced by cf_generator(), and is_valid_town_code().
FOURTEEN
#define FOURTEEN 14
Definition at line 33 of file cf_generator.h.
G
#define G 'G'
Definition at line 59 of file cf_generator.h.
H
#define H 'H'
Definition at line 60 of file cf_generator.h.
HUNDRED
#define HUNDRED 100
Definition at line 48 of file cf_generator.h.
I
#define I 'I'
Definition at line 61 of file cf_generator.h.
J
#define J 'J'
Definition at line 62 of file cf_generator.h.
K
#define K 'K'
Definition at line 63 of file cf_generator.h.
L
#define L 'L'
Definition at line 64 of file cf_generator.h.
M
#define M 'M'
Definition at line 65 of file cf_generator.h.
Referenced by birth_date_code(), and is_valid_sex().
MAX_YEAR
#define MAX_YEAR 2017
Definition at line 51 of file cf_generator.h.
MIN_YEAR
#define MIN_YEAR 1900
Definition at line 50 of file cf_generator.h.
N
#define N 'N'
Definition at line 66 of file cf_generator.h.
NINE
#define NINE 9
Definition at line 28 of file cf_generator.h.
NINETEEN
#define NINETEEN 19
Definition at line 38 of file cf_generator.h.
O
#define O 'O'
Definition at line 67 of file cf_generator.h.
ONE
#define ONE 1
Definition at line 20 of file cf_generator.h.
P
#define P 'P'
Definition at line 68 of file cf_generator.h.
Q
#define Q 'Q'
Definition at line 69 of file cf_generator.h.
R
#define R 'R'
Definition at line 70 of file cf_generator.h.
S
#define S 'S'
Definition at line 71 of file cf_generator.h.
SEVEN
#define SEVEN 7
Definition at line 26 of file cf_generator.h.
SEVENTEEN
#define SEVENTEEN 17
Definition at line 36 of file cf_generator.h.
SIX
#define SIX 6
Definition at line 25 of file cf_generator.h.
Referenced by cf_generator().
SIXTEEN
#define SIXTEEN 16
Definition at line 35 of file cf_generator.h.
Referenced by is_valid_cf_code().
T
#define T 'T'
Definition at line 72 of file cf_generator.h.
TEN
#define TEN 10
Definition at line 29 of file cf_generator.h.
Referenced by is_valid_date().
THIRTEEN
#define THIRTEEN 13
Definition at line 32 of file cf_generator.h.
THIRTYONE
#define THIRTYONE 31
Definition at line 46 of file cf_generator.h.
THOUSAND
#define THOUSAND 1000
Definition at line 49 of file cf_generator.h.
THREE
#define THREE 3
Definition at line 22 of file cf_generator.h.
Referenced by is_valid_coded_surname_name().
TWELVE
#define TWELVE 12
Definition at line 31 of file cf_generator.h.
TWENTY
#define TWENTY 20
Definition at line 39 of file cf_generator.h.
TWENTYFIVE
#define TWENTYFIVE 25
Definition at line 44 of file cf_generator.h.
TWENTYFOUR
#define TWENTYFOUR 24
Definition at line 43 of file cf_generator.h.
TWENTYONE
#define TWENTYONE 21
Definition at line 40 of file cf_generator.h.
TWENTYSIX
#define TWENTYSIX 26
Definition at line 45 of file cf_generator.h.
TWENTYTHREE
#define TWENTYTHREE 23
Definition at line 42 of file cf_generator.h.
TWENTYTWO
#define TWENTYTWO 22
Definition at line 41 of file cf_generator.h.
TWO
#define TWO 2
Definition at line 21 of file cf_generator.h.
U
#define U 'U'
Definition at line 73 of file cf_generator.h.
V
#define V 'V'
Definition at line 74 of file cf_generator.h.
W
#define W 'W'
Definition at line 75 of file cf_generator.h.
X
#define X 'X'
Definition at line 76 of file cf_generator.h.
Y
#define Y 'Y'
Definition at line 77 of file cf_generator.h.
Z
#define Z 'Z'
Definition at line 78 of file cf_generator.h.
ZERO
#define ZERO 0
Definition at line 19 of file cf_generator.h.
Function Documentation
birth_date_code()
void birth_date_code (char date[], char sex, char code[])
Codifica la data di nascita
Precondition
La data deve essere una stringa avente formato GG/MM/AAAA
Postcondition
la data codificata deve essere una stringa di quattro caratteri
Parameters
date
sex
code
Returns
Definition at line 282 of file cf_generator.c.
References is_valid_date(), is_valid_sex(), and M.
Referenced by cf_generator().
cf_generator()
void cf_generator (char name[], char surname[], char birth_date[], char coded_town[], char sex, char code[])
Genera il codice fiscale
Precondition
la stringa del nome non deve essere vuota
la stringa del cognome non deve essere vuota
La data deve essere una stringa avente formato GG/MM/AAAA
Postcondition
il codice generato deve essere una stringa di 16 caratteri
Parameters
name
surname
birth_date
coded_town
sex
code
Definition at line 437 of file cf_generator.c.
References birth_date_code(), EOS, FOUR, is_valid_date(), is_valid_name(), is_valid_sex(), is_valid_surname(), name_code(), SIX, surname_code(), and ZERO.
ctrl_code()
char ctrl_code (char coded_name[], char coded_surname[], char coded_birth_date[], char coded_birth_place[])
Genera il carattere di controllo
Postcondition
il carattere di controllo deve essere una lettera maiuscola
Parameters
coded_name
coded_surname
coded_birth_date
coded_birth_place
Returns
Definition at line 419 of file cf_generator.c.
References EOS, FIFTEEN, is_valid_coded_surname_name(), and ZERO.
name_code()
void name_code (char name[], char * code)
Codifica il nome
Precondition
la stringa del nome non deve essere vuota
Postcondition
il nome codificato deve essere una stringa di tre lettere
Parameters
name
code
Returns
surname_code()
void surname_code (char surname[], char * code)
Codifica il cognome
Precondition
la stringa del cognome non deve essere vuota
Postcondition
il cognome codificato deve essere una stringa composta da tre lettere
Returns