src/print_code/cf_generator/cf_generator.c File Reference
#include <print_code/cf_generator/cf_generator.h>
*
Functions
int get_consonant (int i, int k, char *string, char *consonants)
void get_consonants (char *string, char *consonants)
void fill_code (char text[], char code[])
void fill_coded_name_four_consonants (char code[], char *consonants)
void name_code (char name[], char code[])
void surname_code (char surname[], char code[])
void birth_date_code (char date[], char sex, char code[])
char ctrl_code (char coded_name[], char coded_surname[], char coded_birth_date[], char coded_birth_place[])
void cf_generator (char name[], char surname[], char birth_date[], char coded_town[], char sex, char code[])
Function Documentation
void birth_date_code (char date[], char sex, char code[])
Codifica la data di nascita
Precondition
La data deve essere una stringa avente formato GG/MM/AAAA
Postcondition
la data codificata deve essere una stringa di quattro caratteri
Parameters
date
sex
code
Returns
Definition at line 162 of file cf_generator.c.
References FIVE, is_valid_date(), is_valid_date_code(), is_valid_sex(), and M.
Referenced by cf_generator().
void cf_generator (char name[], char surname[], char birth_date[], char coded_town[], char sex, char code[])
Genera il codice fiscale
Precondition
la stringa del nome non deve essere vuota
la stringa del cognome non deve essere vuota
La data deve essere una stringa avente formato GG/MM/AAAA
Postcondition
il codice generato deve essere una stringa di 16 caratteri
Parameters
name
surname
birth_date
coded_town
sex
code
Definition at line 234 of file cf_generator.c.
References birth_date_code(), ctrl_code(), FOUR, is_valid_cf_code(), is_valid_date(), is_valid_name(), is_valid_sex(), is_valid_surname(), name_code(), SIX, SIXTEEN, surname_code(), and ZERO.
char ctrl_code (char coded_name[], char coded_surname[], char coded_birth_date[], char coded_birth_place[])
Genera il carattere di controllo
Postcondition
il carattere di controllo deve essere una lettera maiuscola
Parameters
coded_name
coded_surname
coded_birth_date
coded_birth_place
Returns
Definition at line 222 of file cf_generator.c.
References is_valid_coded_surname_name(), is_valid_ctrl_code(), and ZERO.
Referenced by cf_generator().
void fill_code (char text[], char code[])
Definition at line 96 of file cf_generator.c.
References THREE.
Referenced by name_code(), and surname_code().
void fill_coded_name_four_consonants (char code[], char * consonants)
Definition at line 110 of file cf_generator.c.
References ONE, THREE, TWO, and ZERO.
Referenced by name_code().
int get_consonant (int i, int k, char * string, char * consonants)
Definition at line 83 of file cf_generator.c.
Referenced by get_consonants().
void get_consonants (char * string, char * consonants)
Definition at line 89 of file cf_generator.c.
References get_consonant(), and ZERO.
Referenced by name_code().
void name_code (char name[], char code[])
Definition at line 116 of file cf_generator.c.
References fill_code(), fill_coded_name_four_consonants(), FOUR, get_consonants(), is_valid_coded_surname_name(), and is_valid_name().
Referenced by cf_generator().
void surname_code (char surname[], char code[])
Definition at line 125 of file cf_generator.c.
References fill_code(), is_valid_coded_surname_name(), and is_valid_surname().
Referenced by cf_generator().