src/get_data/get_data.c File Reference
#include `../../src/get_data/get_data.h`
*
Functions
static void insert_name (char *name)
const char * get_name ()
static void insert_surname (char *surname)
const char * get_surname ()
static void insert_date (char *date)
const char * get_birth_date ()
static void insert_birth_town (char *town)
const char * get_birth_town ()
char get_sex ()
Variables
static const int MAX_LENGTH_STRING = 100
static const int LENGTH_DATE = 11
static const char * SPEC_CHAR = `%c`
static const char * INSERT_NAME = `Inserisci il nome>`
static const char * INSERT_SURNAME = `Inserisci il cognome>`
static const char * INSERT_DATE = `Inserisci la data di nascita (formato GG/MM/AAAA)>`
static const char * INSERT_TOWN = `Inserisci il comune di nascita>`
static const char * INSERT_SEX = `Inserisci il sesso (M-F)>`
Function Documentation
const char* get_birth_date ()
Acquisisce la data di nascita
Definition at line 56 of file get_data.c.
References insert_date(), is_not_empty_string(), and LENGTH_DATE.
const char* get_birth_town ()
Acquisisce il comune di nascita
Definition at line 71 of file get_data.c.
References insert_birth_town(), is_not_empty_string(), MAX_LENGTH_STRING, and to_upper_string().
const char* get_name ()
Acquisisce il nome
Returns
Definition at line 24 of file get_data.c.
References insert_name(), is_not_empty_string(), MAX_LENGTH_STRING, and to_upper_string().
char get_sex ()
Acquisisce il sesso
Returns
Definition at line 82 of file get_data.c.
References INSERT_SEX, and SPEC_CHAR.
const char* get_surname ()
Acquisisce il cognome
Returns
Definition at line 40 of file get_data.c.
References insert_surname(), is_not_empty_string(), MAX_LENGTH_STRING, and to_upper_string().
static void insert_birth_town (char * town) [static]
Definition at line 66 of file get_data.c.
References INSERT_TOWN.
Referenced by get_birth_town().
static void insert_date (char * date) [static]
Definition at line 51 of file get_data.c.
References INSERT_DATE.
Referenced by get_birth_date().
static void insert_name (char * name) [static]
Definition at line 19 of file get_data.c.
References INSERT_NAME.
Referenced by get_name().
static void insert_surname (char * surname) [static]
Definition at line 35 of file get_data.c.
References INSERT_SURNAME.
Referenced by get_surname().
Variable Documentation
const char* INSERT_DATE = `Inserisci la data di nascita (formato GG/MM/AAAA)>` [static]
Definition at line 15 of file get_data.c.
Referenced by insert_date().
const char* INSERT_NAME = `Inserisci il nome>` [static]
Definition at line 13 of file get_data.c.
Referenced by insert_name().
const char* INSERT_SEX = `Inserisci il sesso (M-F)>` [static]
Definition at line 17 of file get_data.c.
Referenced by get_sex().
const char* INSERT_SURNAME = `Inserisci il cognome>` [static]
Definition at line 14 of file get_data.c.
Referenced by insert_surname().
const char* INSERT_TOWN = `Inserisci il comune di nascita>` [static]
Definition at line 16 of file get_data.c.
Referenced by insert_birth_town().
const int LENGTH_DATE = 11 [static]
Definition at line 11 of file get_data.c.
Referenced by get_birth_date().
const int MAX_LENGTH_STRING = 100 [static]
Definition at line 10 of file get_data.c.
Referenced by get_birth_town(), get_name(), and get_surname().
const char* SPEC_CHAR = `%c` [static]
Definition at line 12 of file get_data.c.
Referenced by get_sex().