src/get_data/get_data.h File Reference
#include <stdio.h>
*
#include <stdlib.h>
*
#include <ctype.h>
*
#include <string.h>
*
#include <assert.h>
*
#include <print_code/is_valid/is_valid.h>
*
#include `../../src/get_data/to_upper/to_upper.h`
*
Functions
const char * get_name ()
const char * get_surname ()
const char * get_birth_date ()
const char * get_birth_town ()
char get_sex ()
Function Documentation
const char* get_birth_date ()
Acquisisce la data di nascita
Definition at line 56 of file get_data.c.
References insert_date(), is_not_empty_string(), and LENGTH_DATE.
const char* get_birth_town ()
Acquisisce il comune di nascita
Definition at line 71 of file get_data.c.
References insert_birth_town(), is_not_empty_string(), MAX_LENGTH_STRING, and to_upper_string().
const char* get_name ()
Acquisisce il nome
Returns
Definition at line 24 of file get_data.c.
References insert_name(), is_not_empty_string(), MAX_LENGTH_STRING, and to_upper_string().
char get_sex ()
Acquisisce il sesso
Returns
Definition at line 82 of file get_data.c.
References INSERT_SEX, and SPEC_CHAR.
const char* get_surname ()
Acquisisce il cognome
Returns
Definition at line 40 of file get_data.c.
References insert_surname(), is_not_empty_string(), MAX_LENGTH_STRING, and to_upper_string().