src/print_code/is_valid/is_valid.c File Reference
#include `is_valid.h`
*
Macros
#define ZERO 0
#define ONE 1
#define TWO 2
#define THREE 3
#define FOUR 4
#define FIVE 5
#define SIX 6
#define SEVEN 7
#define EIGHT 8
#define NINE 9
#define TEN 10
#define TWELVE 12
#define THIRTEEN 13
#define FOURTEEN 14
#define SIXTEEN 16
#define THIRTYONE 31
#define ASCII 48
#define HUNDRED 100
#define THOUSAND 1000
#define MIN_YEAR 1900
#define MAX_YEAR 2018
#define SLASH '/'
#define F 'F'
#define M 'M'
#define SPACE ' '
#define APOSTROPHE '\''
#define EMPTY_STRING ``
Functions
bool is_valid_coded_surname_name (char *code)
bool is_valid_name_surname (char *surname)
bool is_valid_date (char *date)
bool is_valid_ctrl_code (char code)
bool is_valid_town_code (char *code)
bool is_not_empty_string (char *string)
bool is_valid_sex (char sex)
bool is_valid_town (char *town)
bool are_valid_data (char *name, char *surname, char *date, char *coded_town, char sex)
bool is_valid_cf_code (char *code)
bool is_valid_date_code (char *code)
Macro Definition Documentation
#define APOSTROPHE '\''
Definition at line 35 of file is_valid.c.
#define ASCII 48
Definition at line 26 of file is_valid.c.
#define EIGHT 8
Definition at line 18 of file is_valid.c.
#define EMPTY_STRING ``
Definition at line 36 of file is_valid.c.
Referenced by is_not_empty_string(), and is_valid_town().
#define F 'F'
Definition at line 32 of file is_valid.c.
Referenced by is_valid_sex().
#define FIVE 5
Definition at line 15 of file is_valid.c.
Referenced by birth_date_code(), is_valid_date_code(), and read_birth_place_code().
#define FOUR 4
Definition at line 14 of file is_valid.c.
Referenced by cf_generator(), is_valid_town_code(), and name_code().
#define FOURTEEN 14
Definition at line 23 of file is_valid.c.
#define HUNDRED 100
Definition at line 27 of file is_valid.c.
#define M 'M'
Definition at line 33 of file is_valid.c.
Referenced by birth_date_code(), and is_valid_sex().
#define MAX_YEAR 2018
Definition at line 30 of file is_valid.c.
#define MIN_YEAR 1900
Definition at line 29 of file is_valid.c.
#define NINE 9
Definition at line 19 of file is_valid.c.
#define ONE 1
Definition at line 11 of file is_valid.c.
Referenced by repeat().
#define SEVEN 7
Definition at line 17 of file is_valid.c.
#define SIX 6
Definition at line 16 of file is_valid.c.
Referenced by cf_generator().
#define SIXTEEN 16
Definition at line 24 of file is_valid.c.
Referenced by cf_generator(), and is_valid_cf_code().
#define SLASH '/'
Definition at line 31 of file is_valid.c.
#define SPACE ' '
Definition at line 34 of file is_valid.c.
#define TEN 10
Definition at line 20 of file is_valid.c.
Referenced by is_valid_date().
#define THIRTEEN 13
Definition at line 22 of file is_valid.c.
#define THIRTYONE 31
Definition at line 25 of file is_valid.c.
#define THOUSAND 1000
Definition at line 28 of file is_valid.c.
#define THREE 3
Definition at line 13 of file is_valid.c.
Referenced by is_valid_coded_surname_name().
#define TWELVE 12
Definition at line 21 of file is_valid.c.
#define TWO 2
Definition at line 12 of file is_valid.c.
#define ZERO 0
Definition at line 10 of file is_valid.c.
Referenced by cf_generator(), ctrl_code(), is_not_empty_string(), is_valid_name_surname(), is_valid_town(), and to_upper_string().
Function Documentation
bool are_valid_data (char * name, char * surname, char * date, char * coded_town, char sex)
Verifica la correttezza dei dati immessi
Parameters
name
surname
date
coded_town
sex
Returns
Definition at line 123 of file is_valid.c.
References is_valid_date(), is_valid_name_surname(), is_valid_sex(), and is_valid_town_code().
Referenced by print_code().
bool is_not_empty_string (char * string)
Verifica che la stringa non sia vuola
Parameters
string
Returns
Definition at line 111 of file is_valid.c.
References EMPTY_STRING, and ZERO.
Referenced by get_birth_date(), get_birth_town(), get_name(), get_surname(), and read_birth_place_code().
bool is_valid_cf_code (char * code)
Verifica che il codice fiscale abbia il giusto formato
Parameters
code
Returns
Definition at line 144 of file is_valid.c.
References SIXTEEN.
Referenced by cf_generator().
bool is_valid_coded_surname_name (char * code)
Verifica che il codice del cognome e del nome siano corretti
Parameters
code
Returns
Definition at line 45 of file is_valid.c.
References THREE.
Referenced by ctrl_code(), name_code(), and surname_code().
bool is_valid_ctrl_code (char code)
Verifica che il carattere di controllo sia una lettera maiuscola
Parameters
code
Returns
Definition at line 96 of file is_valid.c.
Referenced by ctrl_code().
bool is_valid_date (char * date)
Verifica che la data sia stata inserita nel giusto formato
Parameters
date
Returns
Definition at line 92 of file is_valid.c.
References TEN.
Referenced by are_valid_data(), birth_date_code(), and cf_generator().
bool is_valid_date_code (char * code)
Verifica che il codice abbia il giusto formato
Parameters
code
Returns
Definition at line 159 of file is_valid.c.
References FIVE.
Referenced by birth_date_code().
bool is_valid_name_surname (char * name)
Verifica la correttezza del nome e del cognome
Parameters
name
Returns
Definition at line 56 of file is_valid.c.
References ZERO.
Referenced by are_valid_data(), cf_generator(), name_code(), and surname_code().
bool is_valid_sex (char sex)
Verifica che il sesso sia rappresentato da un M o da una F
Parameters
sex
Returns
Definition at line 115 of file is_valid.c.
References F, and M.
Referenced by are_valid_data(), birth_date_code(), and cf_generator().
bool is_valid_town (char * town)
Definition at line 119 of file is_valid.c.
References EMPTY_STRING, and ZERO.
bool is_valid_town_code (char * code)
Verifica che il codice catastale sia nel giusto formato
Parameters
code
Returns
Definition at line 107 of file is_valid.c.
References FOUR.
Referenced by are_valid_data(), and read_birth_place_code().