src/print_result/is_valid/is_valid.h File Reference
#include <stdbool.h>
#include <string.h>
#include <stdio.h>
#include <ctype.h>
#include `../../../src/print_result/read_birth_place/read_birth_place.h`
Macros
#define ZERO 0
#define ONE 1
#define TWO 2
#define THREE 3
#define FOUR 4
#define FIVE 5
#define SIX 6
#define SEVEN 7
#define EIGHT 8
#define NINE 9
#define TEN 10
#define TWELVE 12
#define THIRTEEN 13
#define FOURTEEN 14
#define SIXTEEN 16
#define THIRTYONE 31
#define ASCII 48
#define HUNDRED 100
#define THOUSAND 1000
#define MIN_YEAR 1900
#define MAX_YEAR 2017
#define SLASH '/'
#define F 'F'
#define M 'M'
#define SPACE ' '
#define APOSTROPHE '\''
#define EMPTY_STRING ``
Functions
bool is_valid_coded_surname_name (char *code)
bool is_valid_name (char *name)
bool is_valid_surname (char *surname)
bool is_valid_date (char *date)
bool is_valid_ctrl_code (char code)
bool is_valid_town_code (char *code)
bool is_valid_date_code (char *code)
bool is_valid_sex (char sex)
bool is_valid_cf_code (char *code)
bool is_not_empty_string (char *string)
bool is_valid_data (char *name, char *surname, char *date, char *coded_town, char sex)
Macro Definition Documentation
APOSTROPHE
#define APOSTROPHE '\''
Definition at line 43 of file is_valid.h.
ASCII
#define ASCII 48
Definition at line 34 of file is_valid.h.
EIGHT
#define EIGHT 8
Definition at line 26 of file is_valid.h.
EMPTY_STRING
#define EMPTY_STRING ``
Definition at line 44 of file is_valid.h.
Referenced by is_not_empty_string(), and is_valid_town().
F
#define F 'F'
Definition at line 40 of file is_valid.h.
FIVE
#define FIVE 5
Definition at line 23 of file is_valid.h.
FOUR
#define FOUR 4
Definition at line 22 of file is_valid.h.
FOURTEEN
#define FOURTEEN 14
Definition at line 31 of file is_valid.h.
HUNDRED
#define HUNDRED 100
Definition at line 35 of file is_valid.h.
M
#define M 'M'
Definition at line 41 of file is_valid.h.
MAX_YEAR
#define MAX_YEAR 2017
Definition at line 38 of file is_valid.h.
MIN_YEAR
#define MIN_YEAR 1900
Definition at line 37 of file is_valid.h.
NINE
#define NINE 9
Definition at line 27 of file is_valid.h.
ONE
#define ONE 1
Definition at line 19 of file is_valid.h.
SEVEN
#define SEVEN 7
Definition at line 25 of file is_valid.h.
SIX
#define SIX 6
Definition at line 24 of file is_valid.h.
SIXTEEN
#define SIXTEEN 16
Definition at line 32 of file is_valid.h.
SLASH
#define SLASH '/'
Definition at line 39 of file is_valid.h.
SPACE
#define SPACE ' '
Definition at line 42 of file is_valid.h.
TEN
#define TEN 10
Definition at line 28 of file is_valid.h.
THIRTEEN
#define THIRTEEN 13
Definition at line 30 of file is_valid.h.
THIRTYONE
#define THIRTYONE 31
Definition at line 33 of file is_valid.h.
THOUSAND
#define THOUSAND 1000
Definition at line 36 of file is_valid.h.
THREE
#define THREE 3
Definition at line 21 of file is_valid.h.
TWELVE
#define TWELVE 12
Definition at line 29 of file is_valid.h.
TWO
#define TWO 2
Definition at line 20 of file is_valid.h.
ZERO
#define ZERO 0
Definition at line 18 of file is_valid.h.
Function Documentation
is_not_empty_string()
bool is_not_empty_string (char * string)
Verifica che la stringa non sia vuola
Parameters
string
Returns
Definition at line 88 of file is_valid.c.
References EMPTY_STRING, and ZERO.
Referenced by get_birth_date(), get_birth_town(), get_name(), get_surname(), and read_birth_place_code().
is_valid_cf_code()
bool is_valid_cf_code (char * code)
Verifica che il codice fiscale abbia il giusto formato
Parameters
code
Returns
Definition at line 120 of file is_valid.c.
References SIXTEEN.
is_valid_coded_surname_name()
bool is_valid_coded_surname_name (char * code)
Verifica che il codice del cognome e del nome siano corretti
Parameters
code
Returns
Definition at line 17 of file is_valid.c.
References THREE.
Referenced by ctrl_code().
is_valid_ctrl_code()
bool is_valid_ctrl_code (char code)
Verifica che il carattere di controllo sia una lettera maiuscola
Parameters
code
Returns
Definition at line 73 of file is_valid.c.
is_valid_data()
bool is_valid_data (char * name, char * surname, char * date, char * coded_town, char sex)
Verifica la correttezza dei dati immessi
Parameters
name
surname
date
coded_town
sex
Returns
Definition at line 100 of file is_valid.c.
References is_valid_date(), is_valid_name(), is_valid_sex(), is_valid_surname(), and is_valid_town_code().
Referenced by print_result().
is_valid_date()
bool is_valid_date (char * date)
Verifica che la data sia stata inserita nel giusto formato
Parameters
date
Returns
Definition at line 69 of file is_valid.c.
References TEN.
Referenced by birth_date_code(), cf_generator(), and is_valid_data().
is_valid_date_code()
bool is_valid_date_code (char * code)
Parameters
code
Returns
Definition at line 135 of file is_valid.c.
References FIVE.
is_valid_name()
bool is_valid_name (char * name)
Verifica la correttezza del cognome
Parameters
name
Returns
Definition at line 32 of file is_valid.c.
References ZERO.
Referenced by cf_generator(), is_valid_data(), and name_code().
is_valid_sex()
bool is_valid_sex (char sex)
Verifica che il sesso sia rappresentato da un M o da una F
Parameters
sex
Returns
Definition at line 92 of file is_valid.c.
References F, and M.
Referenced by birth_date_code(), cf_generator(), and is_valid_data().
is_valid_surname()
bool is_valid_surname (char * surname)
Verifica la correttezza del cognome
Parameters
surname
Returns
Definition at line 28 of file is_valid.c.
References ZERO.
Referenced by cf_generator(), is_valid_data(), and surname_code().
is_valid_town_code()
bool is_valid_town_code (char * code)
Verifica che il codice catastale sia nel giusto formato
Parameters
code
Returns
Definition at line 84 of file is_valid.c.
References FOUR.
Referenced by is_valid_data().