src/print_code/print_code.h File Reference
#include <stdio.h>
*
#include `print_code/cf_generator/cf_generator.h`
*
Functions
void print_code (const char *name, const char *surname, const char *birth_date, const char *coded_town, char sex, FILE *towns)
Function Documentation
void print_code (const char * name, const char * surname, const char * birth_date, const char * coded_town, char sex, FILE * towns)
Stampa a video il codice generato
Parameters
name
surname
birth_date
coded_town
sex
towns
Definition at line 28 of file print_code.c.
References are_valid_data(), not_valid_data(), and print_valid_code().