src/print_code/print_code.c File Reference
#include `print_code.h`
*
Functions
static void print_valid_code (char *name, char *surname, char *birth_date, char *coded_town, char sex)
static void not_valid_data ()
void print_code (char *name, char *surname, char *birth_date, char *coded_town, char sex, FILE *towns)
Variables
static const char * NOT_VALID_DATA
static const char * PRINT_CODE
static const int CODE_LENGTH = 17
Function Documentation
static void not_valid_data () [static]
Definition at line 24 of file print_code.c.
References NOT_VALID_DATA.
Referenced by print_code().
void print_code (char * name, char * surname, char * birth_date, char * coded_town, char sex, FILE * towns)
Stampa a video il codice generato
Parameters
name
surname
birth_date
coded_town
sex
towns
Definition at line 28 of file print_code.c.
References are_valid_data(), not_valid_data(), and print_valid_code().
static void print_valid_code (char * name, char * surname, char * birth_date, char * coded_town, char sex) [static]
Definition at line 18 of file print_code.c.
References cf_generator(), CODE_LENGTH, and PRINT_CODE.
Referenced by print_code().
Variable Documentation
const int CODE_LENGTH = 17 [static]
Definition at line 16 of file print_code.c.
Referenced by print_valid_code().
const char* NOT_VALID_DATA [static]
Initial value:
=
        "\nI dati inseriti non sono tutti corretti\n\n"
Definition at line 10 of file print_code.c.
Referenced by not_valid_data().
const char* PRINT_CODE [static]
Initial value:
=
        "\n================================\n"
        "Codice fiscale: %s"
        "\n================================\n"
Definition at line 12 of file print_code.c.
Referenced by print_valid_code().