src/print_code/read_birth_place/read_birth_place.c File Reference
#include `read_birth_place.h`
*
#include `close/close.h`
*
Functions
static void result_code (char *code, char *result)
static char * get_result (char *birth_place, char *part, char *result)
const char * read_birth_place_code (FILE *places_file, char *birth_place)
void file_not_found ()
Variables
static const int FIFTEEN = 50
static const char * PAUSE = `pause`
static const char * FILE_NOT_FOUND = `File dei codici catastali non trovato\n`
static const int FOURTYSIX = 46
static const int FIVE = 5
static const int ONE = 1
static const int ZERO = 0
static const char eos = '\0'
static const char * VIRGO = `,`
Function Documentation
void file_not_found ()
Stampa un messaggio di errore se il file non è stato trovato
Definition at line 51 of file read_birth_place.c.
References close(), FILE_NOT_FOUND, and PAUSE.
static char* get_result (char * birth_place, char * part, char * result) [static]
Definition at line 27 of file read_birth_place.c.
References FIVE, result_code(), VIRGO, and ZERO.
Referenced by read_birth_place_code().
const char* read_birth_place_code (FILE * places_file, char * birth_place)
Legge da file il codice catastale del comune di nascita
Precondition
il file deve essere aperto
Postcondition
il codice risultante deve essere una stringa di 4 caratteri di cui la prima una lettera e gli altri cifre
Parameters
places_file
birth_place
Returns
Definition at line 35 of file read_birth_place.c.
References FIFTEEN, FIVE, FOURTYSIX, get_result(), is_not_empty_string(), and is_valid_town_code().
static void result_code (char * code, char * result) [static]
Definition at line 21 of file read_birth_place.c.
References eos, ONE, and VIRGO.
Referenced by get_result().
Variable Documentation
const char eos = '\0' [static]
Definition at line 18 of file read_birth_place.c.
Referenced by result_code().
const int FIFTEEN = 50 [static]
Definition at line 11 of file read_birth_place.c.
Referenced by read_birth_place_code().
const char* FILE_NOT_FOUND = `File dei codici catastali non trovato\n` [static]
Definition at line 13 of file read_birth_place.c.
Referenced by file_not_found().
const int FIVE = 5 [static]
Definition at line 15 of file read_birth_place.c.
Referenced by get_result(), and read_birth_place_code().
const int FOURTYSIX = 46 [static]
Definition at line 14 of file read_birth_place.c.
Referenced by read_birth_place_code().
const int ONE = 1 [static]
Definition at line 16 of file read_birth_place.c.
Referenced by result_code().
const char* PAUSE = `pause` [static]
Definition at line 12 of file read_birth_place.c.
Referenced by file_not_found().
const char* VIRGO = `,` [static]
Definition at line 19 of file read_birth_place.c.
Referenced by get_result(), and result_code().
const int ZERO = 0 [static]
Definition at line 17 of file read_birth_place.c.
Referenced by get_result().