src/print_result/read_birth_place/read_birth_place.h File Reference
#include <assert.h>
*
#include <ctype.h>
*
#include <stdio.h>
*
#include <stdbool.h>
*
#include <stdlib.h>
*
#include <string.h>
*
#include `../../../src/close/close.h`
*
#include `../../../src/print_result/is_valid/is_valid.h`
*
Macros
#define FILE_NOT_FOUND `File dei codici catastali non trovato\n`
#define ERROR `Errore di allocazione nella memoria`
#define FILE_NAME `comuni.csv`
#define FILE_MODE `r`
#define PAUSE `PAUSE`
#define EOS '\0'
#define NEW_LINE `\n`
#define VIRGO `,`
#define ZERO 0
#define FOUR 4
#define FIVE 5
#define FOURTYSIX 46
#define STRLEN 50
#define HUNDRED 100
Functions
char * read_birth_place_code (FILE *places_file, char *birth_place)
void file_not_found ()
Macro Definition Documentation
#define EOS '\0'
Definition at line 26 of file read_birth_place.h.
#define ERROR `Errore di allocazione nella memoria`
Definition at line 22 of file read_birth_place.h.
#define FILE_MODE `r`
Definition at line 24 of file read_birth_place.h.
#define FILE_NAME `comuni.csv`
Definition at line 23 of file read_birth_place.h.
#define FILE_NOT_FOUND `File dei codici catastali non trovato\n`
Definition at line 21 of file read_birth_place.h.
Referenced by file_not_found().
#define FIVE 5
Definition at line 31 of file read_birth_place.h.
#define FOUR 4
Definition at line 30 of file read_birth_place.h.
#define FOURTYSIX 46
Definition at line 32 of file read_birth_place.h.
Referenced by read_birth_place_code().
#define HUNDRED 100
Definition at line 34 of file read_birth_place.h.
#define NEW_LINE `\n`
Definition at line 27 of file read_birth_place.h.
#define PAUSE `PAUSE`
Definition at line 25 of file read_birth_place.h.
#define STRLEN 50
Definition at line 33 of file read_birth_place.h.
Referenced by read_birth_place_code().
#define VIRGO `,`
Definition at line 28 of file read_birth_place.h.
#define ZERO 0
Definition at line 29 of file read_birth_place.h.
Function Documentation
void file_not_found ()
Stampa un messaggio di errore se il file non è stato trovato
Definition at line 37 of file read_birth_place.c.
References close(), FILE_NOT_FOUND, and PAUSE.
char* read_birth_place_code (FILE * places_file, char * birth_place)
Legge da file il codice catastale del comune di nascita
Precondition
il file deve essere aperto
Postcondition
il codice risultante deve essere una stringa di 4 caratteri di cui la prima una lettera e gli altri cifre
Parameters
places_file
birth_place
Returns
Definition at line 24 of file read_birth_place.c.
References FIVE, FOURTYSIX, is_not_empty_string(), is_valid_town_code(), and STRLEN.