src/get_data/to_upper/to_upper.c File Reference
#include `to_upper.h`
*
Functions
void to_upper_string (char *string)
Variables
static const int ZERO = 0
Function Documentation
void to_upper_string (char * string)
Rende maiuscole tutte le lettere minuscole presenti nella stringa
Parameters
string
Definition at line 12 of file to_upper.c.
References ZERO.
Referenced by get_birth_town(), get_name(), and get_surname().
Variable Documentation
const int ZERO = 0 [static]
Definition at line 10 of file to_upper.c.
Referenced by to_upper_string().