src/get_data/to_upper/to_upper.h File Reference
#include <ctype.h>
#include <string.h>
Macros
#define ZERO 0
Functions
void to_upper_string (char *string)
Macro Definition Documentation
ZERO
#define ZERO 0
Definition at line 14 of file to_upper.h.
Function Documentation
to_upper_string()
void to_upper_string (char * string)
Rende maiuscole tutte le lettere minuscole presenti nella stringa
Parameters
string
Definition at line 10 of file to_upper.c.
References ZERO.
Referenced by get_birth_town(), get_name(), and get_surname().